function cargarCiudades() {
    var regionSeleccionada = document.getElementById("region").value;
    var selectCiudad = document.getElementById("ciudad");
  
    // Limpiar las opciones actuales
    selectCiudad.innerHTML = "";
  
    // Agregar opciones de ciudad según la región seleccionada
    if (regionSeleccionada === "region-arica") {
        agregarCiudad("Arica");
        agregarCiudad("Parinacota");
        agregarCiudad("Putre");
        agregarCiudad("Camarones");
        agregarCiudad("General lagos");
        agregarCiudad("Belen");
        agregarCiudad("Chucuyo");
        agregarCiudad("Caquena");
        agregarCiudad("Visviri");
        agregarCiudad("Codpa");
        agregarCiudad("San Miguel Azapa");
        agregarCiudad("Saxamar");
        agregarCiudad("Tignamar");
    } else if (regionSeleccionada === "region-tarapaca") {
        agregarCiudad("Iquique");
        agregarCiudad("Alto Hospicio");
        agregarCiudad("Pozo Almonte");
        agregarCiudad("Huara");
        agregarCiudad("Pica");
        agregarCiudad("Tarapaca");
        agregarCiudad("Camina");
        agregarCiudad("Colchane");
        agregarCiudad("Matilla");
        agregarCiudad("Ancuaque");
        agregarCiudad("La Tirana");
        agregarCiudad("Pisagua");
        agregarCiudad("Isluga");
        agregarCiudad("Quebrada de Tarapaca");
        agregarCiudad("Guatacondo");
        agregarCiudad("Cariquima");
        agregarCiudad("Sibaya");
        agregarCiudad("Arabilla");
        agregarCiudad("Mamina");
        agregarCiudad("Guanillos");
  
        
    } else if (regionSeleccionada === "region-antofagasta") {
        agregarCiudad("Antofagasta");
        agregarCiudad("Calama");
        agregarCiudad("Taltal");
        agregarCiudad("Mejillones");
        agregarCiudad("Sierra Gorda");
        agregarCiudad("Ollague");
        agregarCiudad("Tocopilla");
        agregarCiudad("San Pedro de Atacama");
        agregarCiudad("Maria Elena");
        agregarCiudad("Cobija");
        agregarCiudad("Toconce");
        agregarCiudad("Toconao");
        agregarCiudad("Catalina");
  
    } else if (regionSeleccionada === "region-atacama") {
        agregarCiudad("Copiapo");
        agregarCiudad("Chañaral");
        agregarCiudad("Huasco");
        agregarCiudad("Caldera");
        agregarCiudad("Vallenar");
        agregarCiudad("Tierra Amarilla");
        agregarCiudad("Diego de Almagro");
        agregarCiudad("Freirina");
        agregarCiudad("Alto del Carmen");
        agregarCiudad("El Salvador");
        agregarCiudad("Carrizal Bajo");
        agregarCiudad("Huasco Bajo");
        agregarCiudad("Nantoco");
        agregarCiudad("Bahia Inglesa");
        agregarCiudad("Potrerillos");
        agregarCiudad("Cachiyuyo");
        agregarCiudad("San Pedro de Atacama");
        agregarCiudad("Puerto Viejo");
        agregarCiudad("Toconao");
  
      } else if (regionSeleccionada === "region-coquimbo") {
        agregarCiudad("Coquimbo");
        agregarCiudad("La Serena");
        agregarCiudad("Combarbala");
        agregarCiudad("Los Vilos");
        agregarCiudad("Salamanca");
        agregarCiudad("Vicuña");
        agregarCiudad("Illapel");
        agregarCiudad("Ovalle");
        agregarCiudad("Andacollo");
        agregarCiudad("Rio Hurtado");
        agregarCiudad("Monte Patria");
        agregarCiudad("Canela");
        agregarCiudad("La Higuera");
        agregarCiudad("Paihuano");
        agregarCiudad("Punitaqui");
        agregarCiudad("Tongoy");
        agregarCiudad("Guanaquero");
        agregarCiudad("Caimanes");
        agregarCiudad("Sotaqui");
        agregarCiudad("Punta Colorada");
        agregarCiudad("Cuzcuz");
        agregarCiudad("San Julian");
        agregarCiudad("Caleta Los Hornos");
        agregarCiudad("Pichidangui");
        agregarCiudad("Tulahuen");
        agregarCiudad("Pisco Elqui");
  
      } else if (regionSeleccionada === "region-valparaiso") {
        agregarCiudad("Valparaiso");
        agregarCiudad("Catemu");
        agregarCiudad("Los Andes");
        agregarCiudad("Casablanca");
        agregarCiudad("Cabildo");
        agregarCiudad("Concon");
        agregarCiudad("Cartagena");
        agregarCiudad("Viña del Mar");
        agregarCiudad("Calle Larga");
        agregarCiudad("Quillota");
        agregarCiudad("Hijuelas");
        agregarCiudad("Zapallar");
        agregarCiudad("San Esteban");
        agregarCiudad("Santa Maria");
        agregarCiudad("La Ligua");
        agregarCiudad("Algarrobo");
        agregarCiudad("Quintero");
        agregarCiudad("La Calera");
        agregarCiudad("San Antonio");
        agregarCiudad("Nogales");
        agregarCiudad("Rinconada");
        agregarCiudad("Llay Llay");
        agregarCiudad("San Felipe");
        agregarCiudad("La Cruz");
        agregarCiudad("El Tabo");
        agregarCiudad("Santo Domingo");
        agregarCiudad("Putaendo");
        agregarCiudad("Quilpue");
        agregarCiudad("El Quisco");
        agregarCiudad("Villa Alemana");
        agregarCiudad("Puchuncavi");
        agregarCiudad("Juan Fernandez");
        agregarCiudad("Isla de Pascua");
        agregarCiudad("Limache");
        agregarCiudad("Papudo");
        agregarCiudad("Petorca");
        agregarCiudad("Panquehue");
        agregarCiudad("Olmue");
        agregarCiudad("Gran Valparaiso");
        agregarCiudad("Hanga Roa");
        agregarCiudad("El Melon");
        agregarCiudad("Laguna Verde");
  
      } else if (regionSeleccionada === "region-metropolitana") {
        agregarCiudad("Santiago");
        agregarCiudad("El Monte");
        agregarCiudad("Cerrillos");
        agregarCiudad("San Pedro");
        agregarCiudad("Colina");
        agregarCiudad("Maria Pinto");
        agregarCiudad("Alhue");
        agregarCiudad("Conchali");
        agregarCiudad("San Jose de Maipo");
        agregarCiudad("Calera de Tango");
        agregarCiudad("Buin");
        agregarCiudad("Curacavi");
        agregarCiudad("Talagante");
        agregarCiudad("Tiltil");
        agregarCiudad("Melipilla");
        agregarCiudad("Renca");
        agregarCiudad("Calera de Tango");
        agregarCiudad("Lampa");
        agregarCiudad("Peñaflor");
        agregarCiudad("Paine");
        agregarCiudad("Pirque");
        agregarCiudad("San Bernardo");
  
      } else if (regionSeleccionada === "region-ohiggins") {
        agregarCiudad("Ohiggins");
        agregarCiudad("Nancagua");
        agregarCiudad("Palmilla");
        agregarCiudad("Graneros");
        agregarCiudad("Machali");
        agregarCiudad("Peumo");
        agregarCiudad("Codegua");
        agregarCiudad("Donihue");
        agregarCiudad("Rancagua");
        agregarCiudad("Las Cabras");
        agregarCiudad("Malloa");
        agregarCiudad("Rengo");
        agregarCiudad("Placilla");
        agregarCiudad("San Fernando");
        agregarCiudad("Pichidegua");
        agregarCiudad("Quinta de Tilcoco");
        agregarCiudad("Lolol");
        agregarCiudad("Chimbarongo");
        agregarCiudad("Peralillo");
        agregarCiudad("Santa Cruz");
        agregarCiudad("Colchagua");
        agregarCiudad("San Vicente de Taguatagua");
        agregarCiudad("Olivar Bajo");
        agregarCiudad("Chepica");
        agregarCiudad("Coltauco");
        agregarCiudad("Pichilemu");
        agregarCiudad("Paredones");
        agregarCiudad("Marchigue");
        agregarCiudad("Poblacion");
        agregarCiudad("Coinco");
        agregarCiudad("Requinoa");
        agregarCiudad("La Estrella");
        agregarCiudad("Mostazal");
        agregarCiudad("Litueche");
        agregarCiudad("Pumanque");
        agregarCiudad("Navidad");
        agregarCiudad("Litueche");
        agregarCiudad("Gultro");
        agregarCiudad("Lo Miranda");
        agregarCiudad("Puente Negro");
        agregarCiudad("La Lajuela");
        agregarCiudad("Coya");
        agregarCiudad("Chanqueahue");
        agregarCiudad("Sewell");
        agregarCiudad("Larmahue");
        agregarCiudad("Pelequen");
        agregarCiudad("Barrancas");
        agregarCiudad("Villa Ohiggins");
        agregarCiudad("La Aguada");
        agregarCiudad("Rapel");
        
      } else if (regionSeleccionada === "region-maule") {
        agregarCiudad("Maule");
        agregarCiudad("Cauquenes");
        agregarCiudad("Linares");
        agregarCiudad("Talca");
        agregarCiudad("Parral");
        agregarCiudad("Constitucion");
        agregarCiudad("Teno");
        agregarCiudad("Sagrada Familia");
        agregarCiudad("Molina");
        agregarCiudad("Empedrado");
        agregarCiudad("Curepto");
        agregarCiudad("San Clemente");
        agregarCiudad("Curico");
        agregarCiudad("San Javier de Loncomilla");
        agregarCiudad("Retiro");
        agregarCiudad("San Rafael");
        agregarCiudad("Yerbas buenas");
        agregarCiudad("Villa Alegre");
        agregarCiudad("Pencahue");
        agregarCiudad("Longavi");
        agregarCiudad("Hualane");
        agregarCiudad("Pelarco");
        agregarCiudad("Vichuquen");
        agregarCiudad("Colbun");
        agregarCiudad("Rauco");
        agregarCiudad("Rio Claro");
        agregarCiudad("Romeral");
        agregarCiudad("Pelluhue");
        agregarCiudad("Licanten");
        agregarCiudad("Chanco");
        agregarCiudad("Nirivilo");
        agregarCiudad("Curanipe");
        agregarCiudad("Lontue");
        agregarCiudad("Putagan");
        agregarCiudad("Quinamavida");
  
      } else if (regionSeleccionada === "region-nuble") {
        agregarCiudad("Chillan");
        agregarCiudad("Quirihue");
        agregarCiudad("El Carmen");
        agregarCiudad("San Carlos");
        agregarCiudad("Yungay");
        agregarCiudad("San Nicolas");
        agregarCiudad("Bulnes");
        agregarCiudad("Chillan Viejo");
        agregarCiudad("Coelemu");
        agregarCiudad("Portezuelo");
        agregarCiudad("San Ignacio");
        agregarCiudad("Pemuco");
        agregarCiudad("Pinto");
        agregarCiudad("Coihueco");
        agregarCiudad("Treguaco");
        agregarCiudad("Ninhue");
        agregarCiudad("Quillon");
        agregarCiudad("Niquen");
        agregarCiudad("Cobquecura");
        agregarCiudad("Ranquil");
        agregarCiudad("San Fabian");
        agregarCiudad("Bulnes");
        agregarCiudad("Cholguan");
        agregarCiudad("Tres Esquinas");
        agregarCiudad("La Vinita");
        agregarCiudad("Ranguelmo");
        agregarCiudad("Emboque");
        agregarCiudad("Quinquegua");
        agregarCiudad("Alto Perales");
        agregarCiudad("Campanario");
        agregarCiudad("Minas del Prado");
        agregarCiudad("Buli");
        agregarCiudad("Agua Buena");
        agregarCiudad("San Gregorio");
        agregarCiudad("Santa Clara");
        agregarCiudad("Zemita");
        agregarCiudad("El Huape");
        agregarCiudad("Virguin");
        agregarCiudad("Bustamante");
        agregarCiudad("Coleal");
        agregarCiudad("Las Mariposas");
        agregarCiudad("Talquipen");
        agregarCiudad("Quinchamali");
        agregarCiudad("Tanilvoro");
        agregarCiudad("General Cruz");
        agregarCiudad("Buchupureo");
  
      } else if (regionSeleccionada === "region-biobio") {
        agregarCiudad("Concepcion");
        agregarCiudad("Cabrero");
        agregarCiudad("Chiguayante");
        agregarCiudad("Los Angeles");
        agregarCiudad("Arauco");
        agregarCiudad("Canete");
        agregarCiudad("Coronel");
        agregarCiudad("Curanilahue");
        agregarCiudad("Santa Barbara");
        agregarCiudad("Lota");
        agregarCiudad("Talcahuano");
        agregarCiudad("San Pedro de la Paz");
        agregarCiudad("Florida");
        agregarCiudad("Mulchen");
        agregarCiudad("Antuco");
        agregarCiudad("Quilaco");
        agregarCiudad("Santa Juana");
        agregarCiudad("Los Alamos");
        agregarCiudad("Negrete");
        agregarCiudad("Hualpen");
        agregarCiudad("San Rosendo");
        agregarCiudad("Yumbel");
        agregarCiudad("Lebu");
        agregarCiudad("Penco");
        agregarCiudad("Nacimiento");
        agregarCiudad("Laja");
        agregarCiudad("Tucapel");
        agregarCiudad("Quilleco");
        agregarCiudad("Contulmo");
        agregarCiudad("Tirua");
        agregarCiudad("Tome");
        agregarCiudad("Hualqui");
        agregarCiudad("Alto Bio Bio");
        agregarCiudad("Bulnes");
        agregarCiudad("Coelemu");
        agregarCiudad("Yungay");
        agregarCiudad("Portezuelo");
        agregarCiudad("El Carmen");
        agregarCiudad("San Ignacio");
        agregarCiudad("Quillon");
        agregarCiudad("Talcamavida");
  
      } else if (regionSeleccionada === "region-araucania") {
        agregarCiudad("Angol");
        agregarCiudad("Nueva Imperial");
        agregarCiudad("Loncoche");
        agregarCiudad("Temuco");
        agregarCiudad("Carahue");
        agregarCiudad("Collipulli");
        agregarCiudad("Curacautin");
        agregarCiudad("Freire");
        agregarCiudad("Cunco");
        agregarCiudad("Padre las casas");
        agregarCiudad("Gorbea");
        agregarCiudad("Lautaro");
        agregarCiudad("Pitrufquen");
        agregarCiudad("Renaico");
        agregarCiudad("Puren");
        agregarCiudad("Ercilla");
        agregarCiudad("Victoria");
        agregarCiudad("Traiguen");
        agregarCiudad("Galvarino");
        agregarCiudad("Los Sauces");
        agregarCiudad("Puerto Saavedra");
        agregarCiudad("Lonquimay");
        agregarCiudad("Curarrehue");
        agregarCiudad("Nueva Tolten");
        agregarCiudad("Pucon");
        agregarCiudad("Lumaco");
        agregarCiudad("Teodoro Schmidt");
        agregarCiudad("Villarica");
        agregarCiudad("Cholchol");
        agregarCiudad("Vilcun");
        agregarCiudad("Perquenco");
        agregarCiudad("Labranza");
        agregarCiudad("Melipeuco");
        agregarCiudad("Nehuentue");
        agregarCiudad("Licanray");
        agregarCiudad("Pillanlelbun");
        agregarCiudad("Capitan Pastene");
        agregarCiudad("Puerto Dominguez");
        agregarCiudad("Queule");
        agregarCiudad("Malalcahuello");
  
      } else if (regionSeleccionada === "region-rios") {
        agregarCiudad("Los Lagos");
        agregarCiudad("La Union");
        agregarCiudad("Futrono");
        agregarCiudad("Panguipulli");
        agregarCiudad("Valdivia");
        agregarCiudad("Corral");
        agregarCiudad("Rio Bueno");
        agregarCiudad("San Jose de Mariquina");
        agregarCiudad("Lanco");
        agregarCiudad("Paillaco");
        agregarCiudad("Lago Ranco");
        agregarCiudad("Mafil");
        agregarCiudad("Niebla");
        agregarCiudad("Antihue");
        agregarCiudad("Pishuinco");
        agregarCiudad("Punucapa");
        agregarCiudad("Mehuin");
        agregarCiudad("Liquine");
        agregarCiudad("Malalhue");
        agregarCiudad("Curinanco");
        agregarCiudad("Puyehue");
        agregarCiudad("Calafquen");
        agregarCiudad("Puerto Fuy");
        agregarCiudad("Conaripe");
        agregarCiudad("Neltume");
        agregarCiudad("Choshuenco");
        agregarCiudad("Nontuela");
        agregarCiudad("Chaihuin");
        agregarCiudad("Pirihueico");
        agregarCiudad("Llifen");
        agregarCiudad("Los Rios");
        agregarCiudad("Riñihue");
        agregarCiudad("Torobayo");
  
      } else if (regionSeleccionada === "region-lagos") {
        agregarCiudad("Puerto Montt");
        agregarCiudad("Ancud");
        agregarCiudad("Puerto Varas");
        agregarCiudad("Castro");
        agregarCiudad("Osorno");
        agregarCiudad("Purranque");
        agregarCiudad("Quellon");
        agregarCiudad("Fresia");
        agregarCiudad("Los Muermos");
        agregarCiudad("Calbuco");
        agregarCiudad("Frutillar");
        agregarCiudad("Rio Negro");
        agregarCiudad("San Pablo");
        agregarCiudad("Chonchi");
        agregarCiudad("Puerto Octay");
        agregarCiudad("Frutaleufu");
        agregarCiudad("Dalcahue");
        agregarCiudad("Maullin");
        agregarCiudad("Llanquihue");
        agregarCiudad("Cochamo");
        agregarCiudad("Quemchi");
        agregarCiudad("Hualaihue");
        agregarCiudad("Puqueldon");
        agregarCiudad("Curaco de Velez");
        agregarCiudad("Queilen");
        agregarCiudad("Chaiten");
        agregarCiudad("San Juan de la Costa");
        agregarCiudad("Quinchao");
        agregarCiudad("Puyehue");
        agregarCiudad("Palena");
        agregarCiudad("Peulla");
        agregarCiudad("Llaulao");
        agregarCiudad("Forrahue");
        agregarCiudad("Achao");
        agregarCiudad("Ayacara");
        agregarCiudad("Chauchil");
        agregarCiudad("Carelmapu");
        agregarCiudad("Chacao");
        agregarCiudad("Aldachildo");
        agregarCiudad("Auchac");
        agregarCiudad("Petrohue");
        agregarCiudad("Bahia Mansa");
        agregarCiudad("Caleta Chaparano");
        agregarCiudad("Cancura");
        agregarCiudad("Puelo");
        agregarCiudad("Caleta Manzano");
  
      } else if (regionSeleccionada === "region-aysen") {
        agregarCiudad("Aysen");
        agregarCiudad("Coyhaique");
        agregarCiudad("Puerto Aysen");
        agregarCiudad("Chile Chico");
        agregarCiudad("Lago Verde");
        agregarCiudad("Cisnes");
        agregarCiudad("Cochrane");
        agregarCiudad("Tortel");
        agregarCiudad("Guaitecas");
        agregarCiudad("Rio Ibañez");
        agregarCiudad("Puerto Chacabuco");
        agregarCiudad("La junta");
        agregarCiudad("Puerto Cisnes");
        agregarCiudad("Balmaceda");
        agregarCiudad("Puyuhuapi");
        agregarCiudad("Villa Amengual");
        agregarCiudad("Caleta Andrade");
        agregarCiudad("Caleta Tortel");
        agregarCiudad("Puerto Ingeniero Ibañez");
        agregarCiudad("Puerto Murta");
        agregarCiudad("Puerto Aguirre");
        agregarCiudad("Villa Cerro Castillo");
        agregarCiudad("Villa Mañihuales");
        agregarCiudad("La tapera");
  
  
      } else if (regionSeleccionada === "region-magallanes") {
        agregarCiudad("Punta Arenas");
        agregarCiudad("Cabo de Hornos");
        agregarCiudad("Natales");
        agregarCiudad("San Gregorio");
        agregarCiudad("Porvenir");
        agregarCiudad("Rio Verde");
        agregarCiudad("Laguna Blanca");
        agregarCiudad("Timaukel");
        agregarCiudad("Primavera");
        agregarCiudad("Torres de Paine");
        agregarCiudad("Puerto Natales");
        agregarCiudad("Antartica");
        agregarCiudad("Puerto Williams");
        agregarCiudad("Cerro Sombrero");
        agregarCiudad("Villa Tehuelche");
        agregarCiudad("Cerro Castillo");
        agregarCiudad("Puerto Eden");
        agregarCiudad("Cameron");
        agregarCiudad("Villa Las Estrellas");
        agregarCiudad("Punta Delgada");
        
  
    }
  }
  
  function agregarCiudad(nombreCiudad) {
    var option = document.createElement("option");
    option.text = nombreCiudad;
    document.getElementById("ciudad").add(option);
  }
  
  // Inicializar las ciudades basándose en la región predeterminada (puedes cambiarlo si es necesario)
  cargarCiudades();